# Generated by Django 5.0.6 on 2025-10-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="wallet_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=1000000.0,
                max_digits=12,
                verbose_name="Saldo da Carteira (R$)",
            ),
        ),
    ]
