# Generated by Django 5.0.6 on 2025-10-30 13:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baseuser_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo da Carteira (R$)'),
        ),
    ]
