# Generated by Django 5.0.6 on 2025-10-31 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_wallet_balance_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("OFERTANTE", "Ofertante"),
                    ("COMPRADOR", "Comprador"),
                    ("AUDITOR", "Auditor"),
                ],
                max_length=10,
                verbose_name="tipo de usuário",
            ),
        ),
        migrations.CreateModel(
            name="AuditorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("phone", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
