# Generated by Django 5.0.6 on 2025-09-01 21:30

import django.utils.timezone
import projects.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=180, verbose_name="Nome do Documento"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=projects.models.document_upload_to,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Upload"
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=180, verbose_name="Nome do Projeto"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descrição Detalhada"),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("REFLORESTAMENTO", "Reflorestamento e Conservação"),
                            ("ENERGIA_RENOVAvel", "Energia Renovável"),
                            ("AGRICULTURA", "Agricultura de Baixo Carbono"),
                            ("GESTAO_RESIDUOS", "Gestão de Resíduos"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Projeto",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=180,
                        verbose_name="Localização (Cidade/Estado)",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "carbon_credits_available",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Créditos de Carbono Disponíveis"
                    ),
                ),
                (
                    "price_per_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Preço por Crédito (R$)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("ACTIVE", "Ativo"),
                            ("VALIDATED", "Validado"),
                            ("COMPLETED", "Concluído"),
                        ],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
                "ordering": ["-created_at"],
            },
        ),
    ]
