# Generated by Django 5.0.6 on 2025-10-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("REFLORESTAMENTO", "Reflorestamento e Conservação"),
                    ("ENERGIA_RENOVAVEL", "Energia Renovável"),
                    ("AGRICULTURA", "Agricultura de Baixo Carbono"),
                    ("GESTAO_RESIDUOS", "Gestão de Resíduos"),
                    ("OUTRO", "Outro"),
                ],
                max_length=20,
                verbose_name="Tipo de Projeto",
            ),
        ),
    ]
