# Generated by Django on 2025-10-31
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_project_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="validated_by",
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_projects",
                null=True,
                blank=True,
                verbose_name="Validado por",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="validated_at",
            field=models.DateTimeField(null=True, blank=True, verbose_name="Data de Validação"),
        ),
    ]
