# Generated by Django 5.0.6 on 2025-11-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_add_validation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projects/images/",
                verbose_name="Imagem do Projeto",
            ),
        ),
    ]
