# Generated by Django 5.0.6 on 2025-10-14 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        ("projects", "0003_alter_project_project_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="projects.project",
                verbose_name="Projeto",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["buyer"], name="marketplace_buyer_i_e20c48_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["project"], name="marketplace_project_02ea65_idx"
            ),
        ),
    ]
