# Generated by Django 5.0.6 on 2025-10-31 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_alter_transaction_project_and_more"),
        ("projects", "0004_add_validation_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("APPROVED", "Aprovado"),
                    ("REJECTED", "Rejeitado"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Status da Transação",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="marketplace_status_75e8b7_idx"),
        ),
    ]
